server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  cloud:
    gateway:
      # --- ДОДАЄМО НАЛАШТУВАННЯ CORS ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://35.194.43.217.nip.io"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # 1. МАРШРУТ ДЛЯ СТАТИКИ
        - id: react-static
          uri: http://react-frontend:80
          predicates:
            - Path=/static/**, /favicon.ico, /manifest.json, /logo*.png

        # 2. МАРШРУТ ДЛЯ ФРОНТЕНДУ
        - id: react-frontend
          uri: http://react-frontend:80
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>.*), /$\{segment}

        # 3. МАРШРУТ ДЛЯ БЕКЕНДУ (BOOKS)
        - id: books-service
          uri: http://books-service:8082
          predicates:
            - Path=/api/book/**, /api/author/**

        # --- ДОДАЄМО МАРШРУТ ДЛЯ ПРОФІЛЮ ---
        # Оскільки фронтенд тепер робить fetch('/profile')
        - id: user-profile
          uri: lb://gateway # Або просто не додавати, якщо шлюз сам має цей контролер
          predicates:
            - Path=/profile